const zones = [
    { label: 'Adabar', value: 'adabar' },
    { label: 'Badda', value: 'badda' },
    { label: 'Bangsal', value: 'bangsal' },
    { label: 'Bhashantek', value: 'bhashantek' },
    { label: 'Cantonment', value: 'cantonment' },
    { label: 'Chowk Bazar', value: 'chowk_bazar' },
    { label: 'Darus Salam', value: 'darus_salam' },
    { label: 'Demra', value: 'demra' },
    { label: 'Dhanmondi', value: 'dhanmondi' },
    { label: 'Gendaria', value: 'gendaria' },
    { label: 'Gulshan', value: 'gulshan' },
    { label: 'Hatirjheel', value: 'hatirjheel' },
    { label: 'Hazaribagh', value: 'hazaribagh' },
    { label: 'Jatrabari', value: 'jatrabari' },
    { label: 'Kadamtali', value: 'kadamtali' },
    { label: 'Kafrul', value: 'kafrul' },
    { label: 'Kalabagan', value: 'kalabagan' },
    { label: 'Kamrangirchar', value: 'kamrangirchar' },
    { label: 'Khilgaon', value: 'khilgaon' },
    { label: 'Khilkhet', value: 'khilkhet' },
    { label: 'Kotwali', value: 'kotwali' },
    { label: 'Lalbagh', value: 'lalbagh' },
    { label: 'Mirpur Model', value: 'mirpur_model' },
    { label: 'Mohammadpur', value: 'mohammadpur' },
    { label: 'Motijheel', value: 'motijheel' },
    { label: 'Mugda', value: 'mugda' },
    { label: 'New Market', value: 'new_market' },
    { label: 'Pallabi', value: 'pallabi' },
    { label: 'Paltan', value: 'paltan' },
    { label: 'Ramna', value: 'ramna' },
    { label: 'Rampura', value: 'rampura' },
    { label: 'Sabujbagh', value: 'sabujbagh' },
    { label: 'Shah Ali', value: 'shah_ali' },
    { label: 'Shahbag', value: 'shahbag' },
    { label: 'Shahjahanpur', value: 'shahjahanpur' },
    { label: 'Sher-e-Bangla Nagar', value: 'sher_e_bangla_nagar' },
    { label: 'Shyampur', value: 'shyampur' },
    { label: 'Sutrapur', value: 'sutrapur' },
    { label: 'Tejgaon Industrial Area', value: 'tejgaon_industrial_area' },
    { label: 'Tejgaon', value: 'tejgaon' },
    { label: 'Turag', value: 'turag' },
    { label: 'Uttara', value: 'uttara' },
    { label: 'Vatara', value: 'vatara' },
    { label: 'Wari', value: 'wari' }
];

export default zones;
